/** Warm Editorial design system — ported from the Google Stitch export.
 *  Compiles a static stylesheet (css/site.css); the site ships no Tailwind runtime. */
module.exports = {
  darkMode: "class",
  content: [
    "../index.html",
    "../services/index.html",
    "../faq/index.html",
    "../contact/index.html",
    "../work/index.html",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#33302d",
        "background": "#161311",
        "tertiary-fixed-dim": "#ccc5c0",
        "on-secondary-fixed-variant": "#454747",
        "on-surface": "#e9e1dd",
        "tertiary": "#ccc5c0",
        "outline": "#a38c7c",
        "primary-fixed-dim": "#ffb77d",
        "on-secondary": "#2f3130",
        "primary-fixed": "#ffdcc3",
        "on-surface-variant": "#dbc2b0",
        "secondary": "#c6c7c6",
        "surface-container-highest": "#383432",
        "secondary-container": "#454747",
        "surface-container": "#221f1d",
        "on-tertiary-fixed-variant": "#4a4642",
        "surface": "#161311",
        "on-secondary-fixed": "#1a1c1c",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#6e3900",
        "primary-container": "#d97707",
        "error": "#ffb4ab",
        "on-primary-fixed": "#2f1500",
        "on-tertiary-fixed": "#1e1b18",
        "surface-container-low": "#1e1b19",
        "surface-container-high": "#2d2927",
        "surface-container-lowest": "#100e0c",
        "inverse-surface": "#e9e1dd",
        "surface-tint": "#ffb77d",
        "secondary-fixed": "#e2e2e2",
        "on-error-container": "#ffdad6",
        "surface-bright": "#3c3836",
        "on-tertiary": "#33302c",
        "on-tertiary-container": "#2d2925",
        "primary": "#ffb77d",
        "on-background": "#e9e1dd",
        "outline-variant": "#554336",
        "secondary-fixed-dim": "#c6c7c6",
        "surface-dim": "#161311",
        "error-container": "#93000a",
        "on-primary": "#4d2600",
        "on-primary-container": "#432100",
        "inverse-primary": "#904d00",
        "tertiary-container": "#96908b",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        unit: "4px",
        "container-max": "1280px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-gap": "160px",
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["EB Garamond", "serif"],
        "headline-sm": ["EB Garamond", "serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["EB Garamond", "serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["96px", { lineHeight: "1.0", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "500" }],
        "display-lg-mobile": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
};
