/** K&A Performance design system — LIGHT warm editorial.
 *  Compiles a static stylesheet (css/site.css); the site ships no Tailwind runtime. */
module.exports = {
  darkMode: "class",
  content: [
    "../index.html",
    "../services/index.html",
    "../faq/index.html",
    "../contact/index.html",
    "../work/index.html",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#f6f1e8",
        "on-background": "#241f1b",
        "surface": "#f6f1e8",
        "surface-dim": "#ece4d6",
        "surface-bright": "#fffdf9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1ebdf",
        "surface-container": "#ece4d6",
        "surface-container-high": "#e5dccb",
        "surface-container-highest": "#ded3c0",
        "on-surface": "#241f1b",
        "on-surface-variant": "#6b5f50",
        "outline": "#a4917b",
        "outline-variant": "#d9cdb9",
        "inverse-surface": "#2f2a25",
        "inverse-on-surface": "#f3ede2",
        "inverse-primary": "#ffb77d",
        "surface-tint": "#b06b16",
        "primary": "#b06b16",
        "on-primary": "#ffffff",
        "primary-container": "#e7c98d",
        "on-primary-container": "#3a2600",
        "primary-fixed": "#ffdcc3",
        "primary-fixed-dim": "#e9a35a",
        "on-primary-fixed": "#2f1500",
        "on-primary-fixed-variant": "#6e3900",
        "secondary": "#5c5750",
        "on-secondary": "#ffffff",
        "secondary-container": "#e6ded0",
        "on-secondary-container": "#3f3a33",
        "secondary-fixed": "#e6ded0",
        "secondary-fixed-dim": "#cfc6b6",
        "on-secondary-fixed": "#26221d",
        "on-secondary-fixed-variant": "#4a463f",
        "tertiary": "#6b5f50",
        "tertiary-container": "#e6ded0",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#2d2925",
        "tertiary-fixed": "#e6ded0",
        "tertiary-fixed-dim": "#cfc6b6",
        "on-tertiary-fixed": "#26221d",
        "on-tertiary-fixed-variant": "#4a463f",
        "error": "#8c1d18",
        "on-error": "#ffffff",
        "error-container": "#f9dedc",
        "on-error-container": "#410e0b",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        unit: "4px",
        "container-max": "1280px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-gap": "160px",
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["EB Garamond", "serif"],
        "headline-sm": ["EB Garamond", "serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["EB Garamond", "serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["96px", { lineHeight: "1.0", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "500" }],
        "display-lg-mobile": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
};
