import { AbsoluteFill, OffthreadVideo, staticFile } from "remotion";
import jamIndex from "../../../config/jam.json";
import {
  LaptopFrame,
  LAPTOP_SCREEN_ASPECT,
  laptopGeometry,
} from "../../components/LaptopFrame";
import { StandIn } from "../../components/StandIn";
import { demoBox } from "./FlatDemo";
import type { TutorialSceneProps } from "./registry";

/**
 * One Jam recording, as listed in config/jam.json.
 *
 * The manifest is in config/ rather than beside the mp4s because
 * assets/captures/ is gitignored: everything in there is regenerated by
 * scripts/capture.ts, and this list is not. The recordings themselves do live in
 * assets/captures/jam/ and are not tracked either, which is why a missing clip
 * has to render as something rather than fail.
 */
export type JamEntry = {
  id: string;
  /** Repo-relative path, e.g. "assets/captures/jam/contrast-devtools.mp4". */
  path: string;
  width: number;
  height: number;
  /** Frame the usable part starts on, if the recording opens on a still window. */
  trimBefore?: number;
  playbackRate?: number;
};

const CLIPS = (jamIndex as { clips: JamEntry[] }).clips;

export function findJamClip(id: string): JamEntry | null {
  return CLIPS.find((c) => c.id === id) ?? null;
}

/**
 * A Jam screen recording inside the laptop frame, or a labelled stand-in.
 *
 * Alex records these by hand: Chrome on a real page, DevTools open, a real
 * pointer clicking through a real panel. There is no script that can produce
 * one, so a beat that needs a recording has to be able to render before the
 * recording exists, and the rule is the showcase reels' rule: a stand-in must
 * be impossible to mistake for a finished shot. It is flat grey, hatched, and
 * it says which clip is missing.
 *
 * The laptop is always 16:10, whatever the recording's own aspect is, for the
 * same reason src/components/LaptopFrame.tsx gives: a laptop is not a container
 * that takes the shape of its contents. A recording wider or taller than 16:10
 * covers the screen and is cropped rather than letterboxed inside the lid.
 */
export const JamClip: React.FC<TutorialSceneProps> = ({ format, beat }) => {
  const id = typeof beat.props?.clipId === "string" ? beat.props.clipId : beat.id;
  const clip = findJamClip(id);
  const box = demoBox(format);

  // Solve the 16:10 screen against the box in both axes, the same way FlatDemo
  // does, so a Jam beat and a drawn beat put their device in the same place.
  let screenWidth = box.width;
  let screenHeight = Math.round(screenWidth / LAPTOP_SCREEN_ASPECT);
  const first = laptopGeometry(screenWidth, screenHeight);
  if (first.frameHeight > box.height) {
    screenHeight = Math.round(screenHeight * (box.height / first.frameHeight));
    screenWidth = Math.round(screenHeight * LAPTOP_SCREEN_ASPECT);
  }

  return (
    <AbsoluteFill>
      <div
        style={{
          position: "absolute",
          left: box.left,
          top: box.top,
          width: box.width,
          height: box.height,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <LaptopFrame screenWidth={screenWidth} screenHeight={screenHeight}>
          {clip === null ? (
            <StandIn
              kind="Jam recording"
              id={id}
              fontSize={Math.round(34 * box.scale)}
            />
          ) : (
            <OffthreadVideo
              src={staticFile(clip.path.replace(/^assets\//, ""))}
              trimBefore={clip.trimBefore ?? 0}
              playbackRate={clip.playbackRate ?? 1}
              muted
              style={{ width: "100%", height: "100%", objectFit: "cover" }}
            />
          )}
        </LaptopFrame>
      </div>
    </AbsoluteFill>
  );
};
